name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest, windows-latest]
        arch: [x86]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
      - name: Check
        shell: bash
        run: |
          python3 -m pip install --upgrade pip
          pip install -e .
          python3 -m unittest discover -v tests
          python3 setup.py install
